from __future__ import annotations

import csv
import re
from pathlib import Path

import pandas as pd


NCU_METRIC_COLUMNS = [
    "ncu_duration_us",
    "ncu_memory_util_pct",
    "ncu_sol_dram_pct",
    "ncu_sol_l1_tex_pct",
    "ncu_sol_l2_pct",
    "ncu_sm_util_pct",
    "ncu_achieved_occupancy_pct",
    "ncu_active_warps_per_sm",
    "ncu_registers_per_thread",
]

_TEXT_METRICS = {
    "ncu_duration_us": "Duration",
    "ncu_memory_util_pct": "Memory [%]",
    "ncu_sol_dram_pct": "SOL DRAM",
    "ncu_sol_l1_tex_pct": "SOL L1/TEX Cache",
    "ncu_sol_l2_pct": "SOL L2 Cache",
    "ncu_sm_util_pct": "SM [%]",
    "ncu_achieved_occupancy_pct": "Achieved Occupancy",
    "ncu_active_warps_per_sm": "Achieved Active Warps Per SM",
    "ncu_registers_per_thread": "Registers Per Thread",
}


def load_ncu_metrics_csv(path: str | Path) -> pd.DataFrame:
    """Load normalized Nsight Compute metrics for analyzer merge."""

    data = pd.read_csv(path)
    if "kernel_name" not in data.columns:
        raise ValueError("NCU metrics CSV must contain kernel_name")

    for column in NCU_METRIC_COLUMNS:
        if column not in data.columns:
            data[column] = pd.NA
        data[column] = pd.to_numeric(data[column], errors="coerce")

    return data[["kernel_name", *NCU_METRIC_COLUMNS]]


def attach_ncu_metrics(profile: pd.DataFrame, metrics: pd.DataFrame | None) -> pd.DataFrame:
    if metrics is None:
        return profile

    merged = profile.copy()
    merged["_normalized_kernel_name"] = merged["kernel_name"].map(_normalize_name)
    normalized_metrics = metrics.copy()
    normalized_metrics["_normalized_kernel_name"] = normalized_metrics["kernel_name"].map(_normalize_name)
    normalized_metrics = normalized_metrics.drop(columns=["kernel_name"])
    normalized_metrics = normalized_metrics.drop_duplicates("_normalized_kernel_name", keep="first")
    merged = merged.merge(normalized_metrics, on="_normalized_kernel_name", how="left")
    return merged.drop(columns=["_normalized_kernel_name"])


def parse_ncu_report_file(path: str | Path, kernel_name: str | None = None) -> dict[str, object]:
    """Parse either text or CSV output generated by Nsight Compute.

    Older Nsight Compute versions emit several CSV dialects depending on flags.
    This parser intentionally accepts both the human-readable text table and
    CSV rows that contain a known metric label plus a numeric value.
    """

    report_path = Path(path)
    text = report_path.read_text(encoding="utf-8", errors="replace")
    row: dict[str, object] = {"kernel_name": kernel_name or _kernel_name_from_path(report_path)}
    row.update({column: pd.NA for column in NCU_METRIC_COLUMNS})

    _parse_text_metrics(text, row)
    _parse_csv_like_metrics(text, row)
    return row


def _parse_text_metrics(text: str, row: dict[str, object]) -> None:
    for column, label in _TEXT_METRICS.items():
        values = []
        for line in text.splitlines():
            stripped = line.strip()
            if not stripped.startswith(label):
                continue
            numeric_values = _numeric_values(stripped)
            if numeric_values:
                values.append(numeric_values[-1])
        if values:
            row[column] = sum(values) / len(values)


def _parse_csv_like_metrics(text: str, row: dict[str, object]) -> None:
    for fields in csv.reader(text.splitlines()):
        if not fields:
            continue
        joined = " ".join(field.strip() for field in fields)
        for column, label in _TEXT_METRICS.items():
            if label not in joined:
                continue
            numeric_values = _numeric_values(joined)
            if numeric_values:
                row[column] = numeric_values[-1]


def _numeric_values(text: str) -> list[float]:
    return [float(value) for value in re.findall(r"(?<![A-Za-z])-?\d+(?:\.\d+)?", text)]


def _kernel_name_from_path(path: Path) -> str:
    name = path.name
    for suffix in ("_ncu.txt", "_ncu.csv", ".ncu.txt", ".ncu.csv", ".txt", ".csv"):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return path.stem


def _normalize_name(value: object) -> str:
    return str(value).strip().lower().replace("-", "_")
